
name: Deploy workflow (called from stage deploy workflow)

#https://docs.github.com/en/actions/using-workflows/reusing-workflows#calling-a-reusable-workflow

on:
  workflow_call:
    secrets:
      NZSHM22_SOLVIS_API_KEY:
        required: true
      NZSHM22_SOLVIS_API_URL:
        required: true
      NZSHM22_TOSHI_API_ENABLED:
        required: true
      NZSHM22_TOSHI_API_KEY:
        required: true
      NZSHM22_TOSHI_API_URL:
        required: true
      SLS_OFFLINE:
        required: true
      STAGE:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [15.x]
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm install
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_TOSHI_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_TOSHI_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Serverless Deploy ....
        run: npm run-script deploy
        env:
          STAGE: ${{secrets.STAGE}}
          NZSHM22_SOLVIS_API_KEY: ${{ secrets.NZSHM22_SOLVIS_API_KEY }}
          NZSHM22_SOLVIS_API_URL: ${{ secrets.NZSHM22_SOLVIS_API_URL }}
          NZSHM22_TOSHI_API_ENABLED: ${{ secrets.NZSHM22_TOSHI_API_ENABLED }}
          NZSHM22_TOSHI_API_KEY: ${{ secrets.NZSHM22_TOSHI_API_KEY }}
          NZSHM22_TOSHI_API_URL: ${{ secrets.NZSHM22_TOSHI_API_URL }}
          SLS_OFFLINE: ${{ secrets.SLS_OFFLINE }}
