name: Deploy to TEST on Push to deploy-test

on:
  push:
    branches: [ deploy-test ]

jobs:
  call-test-workflow:
    #https://docs.github.com/en/actions/using-workflows/reusing-workflows#calling-a-reusable-workflow
    uses: ./.github/workflows/run-tests.yaml

  deploy:
    # needs: call-test-workflow
    runs-on: ubuntu-latest
    environment: AWS_TEST
    strategy:
      matrix:
        node-version: [18.x]
        python-version: [3.9]
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      # - name: Install and list dependencies w Poetry
      #   run: |
      #     poetry install
      #     poetry show

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: upgrade NPM
        run: npm install --location=global npm@latest

      - name: Verify NPM
        run: npm doctor

      - name: Install Dependencies
        run: npm install

      - name: List packages
        run: npm ls

      - name: list files
        run: ls -la .

      - name: Serverless Doctor
        run: npm run-script sls_doctor

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_TOSHI_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_TOSHI_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Serverless Deploy ....
        run: npm run-script deploy
        env:
          STAGE: ${{secrets.STAGE}}
          NZSHM22_SOLVIS_API_KEY: ${{ secrets.NZSHM22_SOLVIS_API_KEY }}
          NZSHM22_SOLVIS_API_URL: ${{ secrets.NZSHM22_SOLVIS_API_URL }}
          NZSHM22_TOSHI_API_ENABLED: ${{ secrets.NZSHM22_TOSHI_API_ENABLED }}
          NZSHM22_TOSHI_API_KEY: ${{ secrets.NZSHM22_TOSHI_API_KEY }}
          NZSHM22_TOSHI_API_URL: ${{ secrets.NZSHM22_TOSHI_API_URL }}
          SLS_OFFLINE: ${{ secrets.SLS_OFFLINE }}
